WebApplication1/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.DAL.Data;
using WebApplication1.Extensions;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CartController : Controller
    {
        private ApplicationDbContext _context;
        private string cartKey = "cart";
        private Cart _cart;

        public CartController(ApplicationDbContext context, Cart cart)
        {
            _context = context;
            _cart = cart;
        }
        public IActionResult Index()
        {
            return View(_cart.Items.Values);
        }
        [Authorize]
        public IActionResult Add(int id, string returnUrl)
        {
            var item = _context.Dishes.Find(id);
            if (item != null)
            {
                _cart.AddToCart(item);
                
            }
            return Redirect(returnUrl);
        }
        public IActionResult Delete(int id)
        {
            _cart.RemoveFromCart(id);
            return RedirectToAction("Index");

        }
    }
}

WebApplication1/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebApplication1.DAL.Data;
using WebApplication1.DAL.Entities;
using WebApplication1.Extensions;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ProductController : Controller
    {
        ApplicationDbContext _context;
        int _pageSize;
        private ILogger _logger;

        public ProductController(ApplicationDbContext context/*, ILogger<ProductController> logger*/)
        {
            _pageSize = 3;
            _context = context;
            //_logger = logger;
        }

        [Route("Catalog")]
        [Route("Catalog/Page_{pageNo}")]
        public IActionResult Index(int? group, int pageNo=1)
        {
            var groupMame = group.HasValue? _context.DishGroups.Find(group.Value)?.GroupName: "all groups";
            //_logger.LogInformation($"info: group={group}, page={pageNo}");
            // Поместить список групп во ViewData
            var dishesFiltered = _context.Dishes.Where(d => !group.HasValue || d.DishGroupId == group.Value);
            ViewData["Groups"] = _context.DishGroups;

            ViewData["CurrentGroup"] = group ?? 0;
            var model = ListViewModel<Dish>.GetModel(dishesFiltered, pageNo, _pageSize);
            if (Request.IsAjaxRequest())
                return PartialView("_listpartial", model);
            else
                return View(model);
        }
    }
}

WebApplication1/Views/Product/Index.cshtml
@model ListViewModel<Dish>

@{
    ViewData["Title"] = "Меню";
    var categories = ViewData["Groups"] as IEnumerable<DishGroup>;
    int currentGroup = (int)ViewData["CurrentGroup"];
    var text = currentGroup != 0
    ? categories
    .FirstOrDefault(g => g.DishGroupId == currentGroup)?
    .GroupName
    : "Все";
}

    <div class="row">
        <div class="col-2">
            <div class="dropdown mt-2">
                <a class="btn btn-secondary dropdown-toggle"
                   asp-action="Index" asp-controller="Product"
                   role="button"
                   id="dropdownMenuLink"
                   data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    @text
                </a>
                <div class="dropdown-menu"
                     aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item"
                       asp-action="Index"
                       asp-controller="Product">Все</a>
                    @foreach (var item in categories)
                    {
                        <a class="dropdown-item"
                           asp-action="Index"
                           asp-controller="Product" asp-route-group="@item.DishGroupId"
                           asp-route-pageNo="1">@item.GroupName</a>
                    }
                </div>
            </div>
        </div>
        <div class="col-10">
            @*<div class="card-deck">
            @foreach (var item in Model)
            {<partial name="_ListItemPartial" model="@item" />
            }
        </div>*@
            <div class="card-group" id="list">
                <partial name="_ListPartial" model="@Model" />
            </div>

            <pager page-current="@Model.CurrentPage" page-total="@Model.TotalPages"
                   action="Index"
                   controller="Product" group-id="@currentGroup"></pager>
        </div>
    </div>

WebApplication1/Views/Product/_ListItemPartial.cshtml
@model Dish
<div class='card m-2 p-1 text-center col-4'>
    <img src="~/Images/@Model.Image"
         alt='NoImage'
         class="card-img-top" />
    <div class="card-body">
        <h5 class="card-title">
            @Model.DishName
        </h5>
        <p class="card-text">
            @Model.Description
        </p>
        <div class="card-text badge badge-secondary">
            <h6>@Model.Calories калорий</h6>
        </div> @{ // Получение текущего адреса
            var request = ViewContext.HttpContext.Request;
            var returnUrl = request.Path + request.QueryString.ToUriComponent(); }
        <!--Разметка кнопки добавления в корзину-->
        <p class="mt-2">
            <a asp-action="Add"
               asp-controller="Cart" asp-route-id="@Model.DishId" asp-route-returnUrl="@returnUrl"
               class="btn btn-primary">
                <i class="fa fa-shopping-cart"></i> В корзину
            </a>
        </p>
    </div>
</div>

WebApplication1/Views/Product/_ListPartial.cshtml
@model ListViewModel<Dish>
@foreach (var item in Model)
{
    <partial name="_ListItemPartial" model="@item" />
}